server:
  port: 8080

spring:
  datasource:
    username: root
    password: tiger
    url: jdbc:mysql://127.0.0.1:3306/jingdong
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/jd/mapper/*Mapper.xml
  type-aliases-package: com.jd.entity

#showSql
logging:
  level:
    com:
      jd:
        mapper: debug